# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/darkowlzz/daemonset-job-terminator
    environment:
      version: 1.0.1
      arch: amd64
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/golang/lint/golint
      - run: golint -set_exit_status $(go list ./...)
      - run: go vet ./...
      - run: go test -v ./...
      - run: go build -o out github.com/darkowlzz/daemonset-job-terminator/app
